### ISSUE TITLE
There is no extension able to load the configuration for "divante_google_translate"

### ISSUE THREAD

**Issue by ITspirit** [DivanteLtd/pimcore-google-translate#2]
Try to enable this bundle on:
Pimcore 6.6 with PHP7.4
after enabling this bundle i get every time:

> There is no extension able to load the configuration for "divante_google_translate" (in "/www/vendor/divante-ltd/pimcore-google-translate/src/GoogleTranslateBundle/Resources/config/pimcore/config.yml"). 

No chance to get it work. Any suggestions?

**Comment by prugala** [comment]
Hello, thank you for a report. Its bug, config file should't be in a repository. Could you create Merge Request? Best way is delete `pimcore` directory.
https://github.com/DivanteLtd/pimcore-google-translate/tree/master/src/GoogleTranslateBundle/Resources/config/pimcore

**Comment by ITspirit** [comment]
Sure PR is coming ;-)

**Comment by prugala** [comment]
@ITspirit 
Thanks, merged. Please check that all works now so I will create first tag :)
