### ISSUE TITLE
Add DeepL support

### ISSUE THREAD

**Issue by kubaplas** [DivanteLtd/pimcore-google-translate#4]

**Comment by bramalho** [comment]
Agree, deepl or other translation providers, me and @kkirsz we are going to start working in a new version of this package exactly for this.
But in this case, the name of this package is not correct, suggestions?

**Comment by prugala** [comment]
@bramalho you can wait. I've started refactor and support for custom providers. I'll open WIP MR tomorrow.
I changed bundle name to: pimcore-translate-bundle
